version: '2'
services:
  odoo13:
    image: genral73/docker-odoo:13.0
    depends_on:
      - db
    ports:
      - "8080:8069"
    tty: true
    command: -- --dev=reload    
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    restart: always             # run as a service
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always             # run as a service
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata  
volumes:
  odoo-web-data:
  odoo-db-data: